
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE,
                      fig.path = "man/figures/")
set.seed(2018-02-17)
```

<div class="row">
  <div class="col-md-6">

Here's a Bayesian linear regression model for the `iris` data using greta:

```
x <- iris$Petal.Length
y <- iris$Sepal.Length
```
```
library(greta)

int <- normal(0, 5)
coef <- normal(0, 3)
sd <- lognormal(0, 3)

mean <- int + coef * x
distribution(y) <- normal(mean, sd)
```
```
m <- model(int, coef, sd)
```

  </div>
  <div class="col-md-6">
  
```
draws <- mcmc(m, n_samples = 1000, chains = 4)
bayesplot::mcmc_trace(draws)
```
```{r vis, echo = FALSE, eval = TRUE, results='hide', message=FALSE, warning=FALSE, fig.height=4, fig.width=6, fig.align="center"}
x <- iris$Petal.Length
y <- iris$Sepal.Length
library(greta)
int <- normal(0, 5)
coef <- normal(0, 3)
sd <- lognormal(0, 3)
mean <- int + coef * x
distribution(y) <- normal(mean, sd)
m <- model(int, coef, sd)
draws <- mcmc(m, n_samples = 1000, chains = 4)
bayesplot::mcmc_trace(draws, facet_args = list(nrow = 3, ncol = 1)) + ggplot2::theme_minimal()
```

  </div>
</div>
