---
output: html_document
---
### Multispecies

Fitting a multispecies model of normally distributed data


#### data
<div class="data">
```{r data_multispecies_binomial, highlight = FALSE}
# make fake data
n_species <- 10
n_env <- 3
n_sites <- 20
n_obs <- 4

env <- matrix(rnorm(n_sites * n_env), nrow = n_sites)
# occupancy <- array(rep(rbinom(n_sites * n_obs, 1, 0.5),n_species), dim=c(n_sites, n_obs, n_species))
occupancy <- matrix(rbinom(n_species * n_sites, n_obs, 0.5), nrow = n_species)
```
</div>

#### greta code
```{r multispecies_binomial_greta}
# load greta
library(greta)

# data
X <- as_data(env)
Y <- as_data(occupancy)
n_env <- ncol(X)

# variables
alpha <- normal(0,10, dim = c(n_species, 1))
beta <- normal(0, 10, dim = c(n_species, n_env))
env_effect <- beta %*% t(X) #not transposed environmental matrix

# matrix addition with `sweep()` create interim variable
eta <- sweep(env_effect, 1, alpha, FUN = '+')

# ilogit of linear predictor
p <- ilogit(eta)

# a single observation means our data are bernoulli distributed
distribution(Y) = binomial(n_obs, p)

# create model object with the things we want samples of
m <- model(alpha, beta)

# plot model structure
plot(m)
```
